version: 2.1

jobs:
    build:
        docker:
            - image: cimg/node:17.7.2
        working_directory: ~/dteruel-website
        steps:
            - checkout
            - run:
                  name: "checking node and npm version"
                  command: node --version
            - run: npm --version
            - run:
                  name: Node Sass
                  command: npm install node-sass

            - run:
                  name: Rebuild Node Sass
                  command: sudo npm rebuild node-sass
            - run:
                  name: "Installing dependencies"
                  command: npm install
            - run: npm run production

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    dteruel-workflow:
        jobs:
            - build
